apiVersion: apps/v1
kind: Deployment
metadata:
  name: trilium
  namespace: trilium
  # annotations: 
  #   argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
      - name: trilium
        image: triliumnext/trilium:latest
        env:
        - name: TRILIUM_PORT
          value: "8080"
        - name: TZ
          value: "America/Chicago"
        volumeMounts:
        - name: trilium-storage
          mountPath: /trilium-data
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8080
      volumes:
      - name: trilium-storage
        # emptyDir: {}