apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guestbook-test

resources:
  - namespace.yaml
  - pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - certificate.yaml
