apiVersion: v1
kind: Service
metadata:
  name: authentik
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: http
  - port: 9443
    targetPort: 9443
    name: https
  selector:
    app: authentik
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: authentik-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: authentik-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: authentik-redis